export const IS_LOADING = 'IS_LOADING';
export const IS_LOADING_WHEN_SEARCHING = 'IS_LOADING_WHEN_SEARCHING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_ARTICLE_ARRAY = 'SET_ARTICLE_ARRAY';
export const SET_ARTICLE_ARRAY_WHEN_SEARCHING = 'SET_ARTICLE_ARRAY_WHEN_SEARCHING';
export const SET_HISTORY_ARRAY = 'SET_HISTORY_ARRAY';